import { createBashTool } from "bash-tool";
import { tool, type ToolSet } from "ai";
import { z } from "zod";
import { Bash, type BashOptions } from "just-bash";

/** Working directory used by the virtual shell when none is given. */
export const DEFAULT_WORKING_DIRECTORY = "/workspace";

/** Tool name used for the sink tool when none is given. */
export const DEFAULT_SINK_TOOL_NAME = "sendFileToUser";

/**
 * Default upper bound for a single delivery, in characters.
 *
 * Most chat backends reject or silently truncate very long messages. Truncating
 * here would quietly drop rows from an aggregated report, so oversized files are
 * rejected with an actionable error instead.
 */
export const DEFAULT_MAX_OUTPUT_LENGTH = 4000;

export interface SinkPayload {
  /** Absolute path of the file inside the virtual filesystem. */
  path: string;
  /** Full file content, exactly as written by the model's bash commands. */
  content: string;
  /** `content.length`, provided so callers do not have to recompute it. */
  characterCount: number;
}

/**
 * Delivers file content to its final destination (a chat message, a websocket,
 * stdout, a file upload, ...).
 *
 * The returned value is never sent back to the model.
 */
export type Sink = (payload: SinkPayload) => Promise<void> | void;

/** Value returned to the model after a successful delivery. */
export interface SinkToolOutput {
  sent: true;
  path: string;
  characterCount: number;
}

export interface SinkOptions {
  /** Destination for the file content. Required to expose the sink tool. */
  sink: Sink;
  /** Tool name exposed to the model. Defaults to {@link DEFAULT_SINK_TOOL_NAME}. */
  toolName?: string;
  /** Overrides the default tool description, e.g. to write it in another language. */
  description?: string;
  /**
   * Maximum number of characters accepted for a single delivery.
   * Set to `Infinity` to disable the check. Defaults to {@link DEFAULT_MAX_OUTPUT_LENGTH}.
   */
  maxOutputLength?: number;
  /** Called right before the sink runs. Useful for progress indicators. */
  onBeforeSend?: (payload: SinkPayload) => Promise<void> | void;
}

export interface CreateBashToolsOptions {
  /** Enables the sink tool. Without it only `bash` / `readFile` / `writeFile` are exposed. */
  sink?: SinkOptions;
  /** Working directory of the virtual shell. Defaults to {@link DEFAULT_WORKING_DIRECTORY}. */
  workingDirectory?: string;
  /** Enables `python3` (CPython compiled to WebAssembly). Defaults to `true`. */
  python?: boolean;
  /** Enables `js-exec` (QuickJS). Defaults to `true`. */
  javascript?: boolean;
  /**
   * Extra `just-bash` options, merged last.
   *
   * Network access stays disabled unless you explicitly pass `network` here.
   * Opening it gives the sandbox an outbound path for whatever data the model
   * placed in the virtual filesystem, so treat it as a deliberate decision.
   */
  bashOptions?: Partial<BashOptions>;
  /** Appended to the tool description generated by `bash-tool`. */
  extraInstructions?: string;
  /** Called before each bash command runs. */
  onBeforeCommand?: (context: { command: string }) => void;
  /** Called after each bash command finishes. */
  onAfterCommand?: (context: {
    command: string;
    exitCode: number;
    stdout: string;
    stderr: string;
  }) => void;
}

export interface BashTools {
  /** Tool set to hand to the AI SDK. */
  tools: ToolSet;
  /** The underlying shell, sharing its virtual filesystem with every tool above. */
  bash: Bash;
}

/** Resolves relative paths against the virtual shell's working directory. */
function resolveVirtualPath(rawPath: string, workingDirectory: string): string {
  const trimmed = rawPath.trim();
  if (!trimmed) {
    throw new Error("path is empty. Pass a path inside the virtual filesystem.");
  }
  return trimmed.startsWith("/") ? trimmed : `${workingDirectory}/${trimmed}`;
}

function buildDefaultDescription(workingDirectory: string, toolName: string): string {
  return [
    "Send an already formatted text file (Markdown, CSV, plain text) from the virtual filesystem",
    "straight to the user. Format the final, user-ready output with bash first, then call",
    `${toolName} once. Do not repeat the delivered content in your final answer: the user already`,
    `received it. Relative paths resolve against ${workingDirectory}.`,
  ].join(" ");
}

/**
 * Builds the sink tool.
 *
 * The tool result deliberately contains no file content. Returning the content
 * would push it back through the model's context, which costs tokens and invites
 * transcription errors when the model copies it into its final answer.
 */
function createSinkTool({
  bash,
  workingDirectory,
  sink,
  toolName,
  description,
  maxOutputLength,
  onBeforeSend,
}: Required<Pick<SinkOptions, "sink">> &
  Omit<SinkOptions, "sink"> & {
    bash: Bash;
    workingDirectory: string;
    toolName: string;
    maxOutputLength: number;
  }) {
  return tool({
    description: description ?? buildDefaultDescription(workingDirectory, toolName),
    inputSchema: z.object({
      path: z
        .string()
        .describe(
          `Path of the file to send. Relative paths resolve against ${workingDirectory}. The file must already be formatted exactly as the user should see it.`
        ),
    }),
    execute: async ({ path }): Promise<SinkToolOutput> => {
      const resolvedPath = resolveVirtualPath(path, workingDirectory);

      let content: string;
      try {
        content = await bash.readFile(resolvedPath);
      } catch (error) {
        throw new Error(
          `Could not read ${resolvedPath} from the virtual filesystem. Create it first with bash or writeFile. (${
            error instanceof Error ? error.message : String(error)
          })`
        );
      }

      if (!content.trim()) {
        throw new Error(`${resolvedPath} is empty. Write the content to send before calling this tool.`);
      }

      if (content.length > maxOutputLength) {
        throw new Error(
          `${resolvedPath} is too long (${content.length} characters, limit ${maxOutputLength}). Narrow the result or summarize it before sending.`
        );
      }

      const payload: SinkPayload = {
        path: resolvedPath,
        content,
        characterCount: content.length,
      };

      await onBeforeSend?.(payload);
      await sink(payload);

      return { sent: true, path: resolvedPath, characterCount: content.length };
    },
  });
}

/**
 * Creates a sandboxed bash tool set whose virtual filesystem has a direct exit
 * to the user.
 *
 * Every returned tool shares one {@link Bash} instance, so a file written by
 * `bash` or `writeFile` can be delivered by the sink tool in the same run.
 * Creating two tool sets gives you two isolated filesystems.
 */
export async function createBashTools({
  sink,
  workingDirectory = DEFAULT_WORKING_DIRECTORY,
  python = true,
  javascript = true,
  bashOptions,
  extraInstructions,
  onBeforeCommand,
  onAfterCommand,
}: CreateBashToolsOptions = {}): Promise<BashTools> {
  const bash = new Bash({
    cwd: workingDirectory,
    // Seed the working directory: with an empty filesystem the cwd does not
    // exist yet and commands such as `ls` fail.
    files: { [`${workingDirectory}/.keep`]: "" },
    python,
    javascript,
    ...bashOptions,
  });

  const { tools } = await createBashTool({
    sandbox: bash,
    destination: workingDirectory,
    ...(extraInstructions ? { extraInstructions } : {}),
    onBeforeBashCall: ({ command }) => {
      onBeforeCommand?.({ command });
      return undefined;
    },
    onAfterBashCall: ({ command, result }) => {
      onAfterCommand?.({
        command,
        exitCode: result.exitCode,
        stdout: result.stdout,
        stderr: result.stderr,
      });
      return undefined;
    },
  });

  const baseTools: ToolSet = {
    bash: tools.bash,
    readFile: tools.readFile,
    writeFile: tools.writeFile,
  };

  if (!sink) {
    return { tools: baseTools, bash };
  }

  const toolName = sink.toolName ?? DEFAULT_SINK_TOOL_NAME;

  return {
    tools: {
      ...baseTools,
      [toolName]: createSinkTool({
        bash,
        workingDirectory,
        toolName,
        maxOutputLength: sink.maxOutputLength ?? DEFAULT_MAX_OUTPUT_LENGTH,
        sink: sink.sink,
        ...(sink.description ? { description: sink.description } : {}),
        ...(sink.onBeforeSend ? { onBeforeSend: sink.onBeforeSend } : {}),
      }),
    },
    bash,
  };
}
